{{- range .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret }}
  namespace: {{ .namespace }}
type: Opaque
data:
  {{- range $key, $value := .secretData }}
  {{- if $value }}
  {{ $key }}: {{ $value }}
  {{- else }}
  {{ $key }}: ""
  {{- end }}
  {{- end }}
---
{{- end }}
